---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuthGlobal
metadata:
  name: "default"
spec:
  allowedNamespaces: [ "*" ]
  defaultMount: "kv"
  defaultAuthMethod: "kubernetes"
  kubernetes:
    audiences: [ "vault" ]
    mount: "kubernetes"
    tokenExpirationSeconds: 600
  vaultConnectionRef: "vault-secrets-operator/default"
