controller:
  ingressClass: haproxy

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  # These are good defaults for developer machines. For production,
  # use 80 and 443. Alternatively, they can be edited live by
  # editing the appropriate configmap in the ingress controller's
  # namespace, and then re-starting (deleting) the IC's pod.

  # These values must be set as strings
  config:
    http-port: "8080"
    https-port: "8443"

  # kind: DaemonSet
  # daemonset:
  #   useHostPort: true
  #   hostPorts:
  #     http: 80
  #     https: 443
