#!/bin/bash
#
# This script allows you to wait for a given pod to reach the Running state, so
# you can use that as a synchronizer for other actions you wish to trigger.
#
set -eou pipefail

CALLED="${BASH_ARGV0:-${BASH_SOURCE:-${0}}}"

timestamp()
{
	date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

err()
{
	say "❌ ${@}"
}

fail()
{
	err "${@}"
	exit ${EXIT_CODE:-1}
}

usage()
{
	[ ${#} -eq 0 ] || err "${@}\n"
	echo -e "usage: ${CALLED} [ -h | -? | --help ] [ -d | --debug ] [ --context context ] [ -n namespace | --namespace namespace ] [ -t timeout | --timeout timeout ] pod" 1>&2
	exit 1
}

ARGS="$(getopt -o "h?dn:t:" -l "help,debug,context:,namespace:,timeout:" -n "${CALLED}" -- "${@}")" || usage

CONTEXT_SET="false"
CONTEXT=""
NAMESPACE_SET="false"
NAMESPACE=""
TIMEOUT_SET="false"
TIMEOUT="1h"
DEBUG="false"

eval set -- "${ARGS}"

while true ; do
	case "${1}" in
		--help | -h | "-?" ) usage ;;

		-- ) shift ; break ;;

		--debug | -d ) DEBUG="true" ; shift ;;

		--context )
			[ "${CONTEXT_SET}" == "false" ] || usage "You may only provide ${1} once"
			CONTEXT_SET="true"
			CONTEXT="${2}"
			[ -n "${CONTEXT}" ] || fail "The context may not be the empty string"
			shift 2
			;;

		--namespace | -n )
			[ "${NAMESPACE_SET}" == "false" ] || usage "You may only provide ${1} once"
			NAMESPACE_SET="true"
			NAMESPACE="${2}"
			[ -n "${NAMESPACE}" ] || fail "The namespace may not be the empty string"
			shift 2
			;;

		--timeout | -t )
			[ "${TIMEOUT_SET}" == "false" ] || usage "You may only provide ${1} once"
			TIMEOUT_SET="true"
			TIMEOUT="${2}"
			[ -n "${TIMEOUT}" ] || fail "The timeout may not be the empty string"
			shift 2
			;;
	esac
done

[ ${#} -eq 1 ] || usage "Must provide the pod's name to wait for"
POD="${1}"
[ -n "${POD}" ] || fail "The pod's name may not be the empty string"

export K="$(type -P kubectl 2>&1)" || fail "Couldn't find kubectl in the path (rc=${?}): ${K}"
export K_ARGS=()
__k()
{
	"${K}" "${K_ARGS[@]}" "${@}"
}

__k_exec()
{
	exec "${K}" "${K_ARGS[@]}" "${@}"
}

CTX_ERR=""
if [ -n "${CONTEXT}" ] ; then
	OUT="$(__k config get-contexts "${CONTEXT}" 2>&1)" || fail "Couldn't validate the context [${CONTEXT}]"
	K_ARGS+=( --context "${CONTEXT}" )
	CTX_ERR=" for the context [${CONTEXT}]"
fi

NS_ERR=""
if [ -n "${NAMESPACE}" ] ; then
	OUT="$(__k get namespace "${NAMESPACE}" 2>&1)" || fail "Couldn't validate the namespace [${NAMESPACE}]${CTX_ERR}"
	K_ARGS+=( --namespace "${NAMESPACE}" )
	NS_ERR=" in the ${NAMESPACE} namespace"
fi


CMD=( __k_exec wait --timeout "${TIMEOUT}" --for=jsonpath="{.status.phase}=Running" "pod/${POD}" )
${DEBUG} && set -x
"${CMD[@]}"
