#!/bin/bash
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${SCRIPT}")"
SOURCE="${BASH_SOURCE:-${0}}"

set -euo pipefail

timestamp()
{
	/usr/bin/date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

ok()
{
	say "✅ ${@}"
}

doing()
{
	say "👉 ${@}"
}

fail()
{
	say "❌ ${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

[ -v CONF_DIR ] || fail "No configuration directory specified in CONF_DIR"
[ -n "${CONF_DIR}" ] || fail "The value of CONF_DIR is empty"
[ -e "${CONF_DIR}" ] || fail "The configuration [${CONF_DIR}] does not exist"
[ -d "${CONF_DIR}" ] || fail "The path [${CONF_DIR}] is not a directory"
[ -r "${CONF_DIR}" ] || fail "The configuration [${CONF_DIR}] is not readable"
[ -x "${CONF_DIR}" ] || fail "The configuration [${CONF_DIR}] is not executable"

#
# Add Cert-Manager
#
doing "Installing Cert-Manager + Trust-Manager"
OUT="$("${BASEDIR}/init-cert-manager" 2>&1)" || \
	fail "Failed to install Cert-Manager and Trust-Manager (rc=${?}):\n${OUT}"

#
# Add HAProxy
#
doing "Installing HAProxy Ingress"
OUT="$("${BASEDIR}/init-hap" "${CONF_DIR}/haproxy-ingress-values.yaml" 2>&1)" || \
	fail "Failed to install HAProxy Ingress (rc=${?}):\n${OUT}"

#
# Create the AWS pull secret on the main namespace, as a template
#
doing "Creating the aws-arkcase-pull template secret"
OUT="$(kubectl --context "local" apply -f "${CONF_DIR}/aws-arkcase-pull.yaml" 2>&1)" || \
	fail "Failed to install the aws-arkcase-pull template secret (rc=${?}):\n${OUT}"

#
# Add the ArkCase helm repository
#
doing "Adding the ArkCase Helm Repo"
OUT="$(helm repo add --force-update arkcase https://arkcase.github.io/ark_helm_charts/ 2>&1)" || \
	fail "Failed to install the ArkCase Helm Repository (rc=${?}):\n${OUT}"

#
# Add the default storage class
#
doing "Installing the HostPath provisioner"
OUT="$(helm --kube-context "local" upgrade --install --create-namespace --namespace hostpath-provisioner hostpath-provisioner arkcase/hostpath-provisioner 2>&1)" || \
	fail "Failed to install the HostPath provisioner (rc=${?}):\n${OUT}"

doing "Installing Vault"
OUT="$("${BASEDIR}/init-vault" 2>&1)" || \
	fail "Failed to install Vault (rc=${?}):\n${OUT}"

doing "Installing Vault Secrets Operator"
OUT="$("${BASEDIR}/init-vault-secrets-operator" 2>&1)" || \
	fail "Failed to install Vault Secrets Operator (rc=${?}):\n${OUT}"

ok "Support resources deployed"
exit 0
