#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -euo pipefail

timestamp()
{
	date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

ok()
{
	say "✅ ${@}"
}

err()
{
	say "❌ ${@}"
}

fail()
{
	err "${@}"
	exit ${EXIT_CODE:-1}
}

cleanup()
{
	[ -n "${NEW_CONFIG:-}" ] && shred -u "${NEW_CONFIG}" &>/dev/null || true
	if [ -n "${CONFIG_ERROR:-}" ] ; then
		[ -n "${CTX_CA_CRT_FILE:-}" ] && shred -u "${CTX_CA_CRT_FILE}" &>/dev/null || true
		[ -n "${CTX_TOKEN_FILE:-}" ] && shred -u "${CTX_TOKEN_FILE}" &>/dev/null || true
	fi
}

CURRENT_USER="$(id -un)"
HOME="$(eval echo ~${CURRENT_USER})"

if [ ! -d "${HOME}" ] ; then
	err "❌ No home directory [${HOME}] for user [${CURRENT_USER}] ... can't configure the Kubeconfig"
	exit 0
fi

export NEW_CONFIG="/etc/kubernetes/admin.conf"
TGT="$(mktemp)"
sudo cat "${NEW_CONFIG}" > "${TGT}"
export NEW_CONFIG="${TGT}"
trap cleanup EXIT
unset TGT

KUBE_DIR="${HOME}/.kube"
OUT="$(mkdir -p "${KUBE_DIR}" 2>&1)" || fail "Couldn't create the directory [${KUBE_DIR}] (rc=${?}): ${OUT}"

get_config_value()
{
	local JSONPATH="${1}"
	kubectl --kubeconfig="${NEW_CONFIG}" config view --raw --output jsonpath="{ ${JSONPATH} }"
}

say "👉 Configuring your K8s cluster access settings"

export CONFIG_ERROR="true"
export KUBECONFIG="${KUBE_DIR}/config"

# Get all the configurations!
CTX_NAME="local"

CTX_CLUSTER="${CTX_NAME}"
CTX_PREFIX=".clusters[0].cluster"
CTX_CA_CRT="$(get_config_value "${CTX_PREFIX}.certificate-authority-data" 2>&1)" || fail "Failed to read the CA certificate data from the new configuration (rc=${?}): ${CTX_CA_CRT}"
CTX_URL="$(get_config_value "${CTX_PREFIX}.server" 2>&1)" || fail "Failed to read the server URL from the new configuration (rc=${?}): ${CTX_URL}"

CTX_USER="${CTX_NAME}"

# Got everything! Now set it up!
CTX_CA_CRT_FILE="${KUBE_DIR}/${CTX_NAME}.crt"

OUT="$( ( base64 -d <<< "${CTX_CA_CRT}" > "${CTX_CA_CRT_FILE}" ) 2>&1 )" || fail "Failed to create the file for the CA certificate data (rc=${?}): ${OUT}"
OUT="$(openssl x509 -noout -in "${CTX_CA_CRT_FILE}" 2>&1)" || fail "Invalid certificate file for the CA certificate (rc=${?}): ${OUT}"

# We're good to go! Add the items!
OUT="$(kubectl config set-cluster "${CTX_CLUSTER}" --certificate-authority="${CTX_CA_CRT_FILE}" --server="${CTX_URL}" --embed-certs=false 2>&1)" || fail "Failed to add the cluster named [${CTX_CLUSTER}] (rc=${?}): ${OUT}"
OUT="$(kubectl config set "clusters.${CTX_CLUSTER}.certificate-authority" "$(readlink -f "${CTX_CA_CRT_FILE}")" 2>&1)" || fail "Failed to set the absolute path for the CA certificate (rc=${?}): ${OUT}"
OUT="$(kubectl config set-credentials "${CTX_USER}" --token="placeholder" --embed-certs=false 2>&1)" || fail "Failed to add the user named [${CTX_USER}] (rc=${?}): ${OUT}"
OUT="$(kubectl config set-context "${CTX_NAME}" --cluster="${CTX_CLUSTER}" --user="${CTX_USER}" 2>&1)" || fail "Failed to add the context named [${CTX_NAME}] (rc=${?}): ${OUT}"

# Now we do the token thing!
ADMIN_NAMESPACE="kube-system"
ADMIN_USER="admin"
if ! kubectl --kubeconfig "${NEW_CONFIG}" --namespace "${ADMIN_NAMESPACE}" get serviceaccount "${ADMIN_USER}" &>/dev/null ; then
	OUT="$(kubectl --kubeconfig "${NEW_CONFIG}" --namespace "${ADMIN_NAMESPACE}" create serviceaccount "${ADMIN_USER}" 2>&1)" || fail "Failed to create the ${ADMIN_USER} service account (rc=${?}): ${OUT}"
fi
ok "Admin service account ready!"

ADMIN_ROLE="cluster-admin"
if ! kubectl --kubeconfig "${NEW_CONFIG}" get clusterrolebinding "${ADMIN_ROLE}:${ADMIN_USER}" &>/dev/null ; then
	OUT="$(kubectl --kubeconfig "${NEW_CONFIG}" create clusterrolebinding "${ADMIN_ROLE}:${ADMIN_USER}" --clusterrole="${ADMIN_ROLE}" --serviceaccount="${ADMIN_NAMESPACE}:${ADMIN_USER}" 2>&1)" || fail "Failed to create the ClusterRoleBinding between ${ADMIN_ROLE} and ${ADMIN_USER}"
fi
ok "ClusterRoleBinding ready!"

DURATION="87600h"
TOKEN="$(kubectl --kubeconfig "${NEW_CONFIG}" --namespace "${ADMIN_NAMESPACE}" create token "${ADMIN_USER}" --duration="${DURATION}" 2>&1)" || fail "Failed to create a bearer token for local cluster admin access (rc=${?}): ${TOKEN}"

CTX_TOKEN_FILE="${KUBE_DIR}/${CTX_NAME}.tok"
OUT="$( ( echo -n "${TOKEN}" > "${CTX_TOKEN_FILE}" ) 2>&1)" || fail "Failed to create the admin user's token file (rc=${?}): ${OUT}"
ok "Token file created!"

OUT="$(kubectl config unset "users.${CTX_USER}.token" 2>&1)" || err "Failed to clear the admin user's placeholder token (rc=${?}): ${OUT}"
OUT="$(kubectl config set "users.${CTX_USER}.tokenFile" "$(readlink -f "${CTX_TOKEN_FILE}")" 2>&1)" || fail "Failed to set the token file for the admin user (rc=${?}): ${OUT}"
ok "Token file configured!"

# Make sure we're using the local context
OUT="$(kubectl --context "${CTX_NAME}" get pods --all-namespaces 2>&1)" || fail "Failed to validate access to the new context '${CTX_NAME}' (rc=${?}): ${OUT}"
OUT="$(kubectl config use-context "${CTX_NAME}" 2>&1)" || fail "Failed to set the current context to '${CTX_NAME}' (rc=${?}): ${OUT}"

# Avoid deletion of files
export CONFIG_ERROR=""
ok "Context configuation complete and verified!"

OUT="$(chown -Rv "${CURRENT_USER}:" "${KUBE_DIR}" 2>&1)" || fail "Failed to set the correct ownership for the config directory (rc=${?}): ${OUT}"
OUT="$(chmod -Rv go-rwx "${KUBE_DIR}" 2>&1)" || fail "Failed to set the correct permissions for the config directory (rc=${?}): ${OUT}"

kubectl config get-contexts
ok "Cluster access configured"
