#!/bin/bash

set -euo pipefail

timestamp()
{
	/usr/bin/date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

doing()
{
	say "👉 ${@}"
}

ok()
{
	say "✅ ${@}"
}

warn()
{
	say "⚠️ ${@}"
}

err()
{
	say "❌ ${@}"
}

fail()
{
	err "${@}"
	exit ${EXIT_CODE:-1}
}

cleanup()
{
	if [ -n "${CONTAINER:-}" ] ; then
		doing "Removing the created container (${CONTAINER}) ..."
		OUT="$(docker container rm --force --volumes "${CONTAINER}" 2>&1)" \
			&& ok "Cleanup complete!" \
			|| err "Couldn't remove the container [${CONTAINER}] (rc=${?}): ${OUT}"
	fi
}

REG="public.ecr.aws"
REPO="arkcase/base"
VER="latest"
IMAGE="${REG}/${REPO}:${VER}"

RC=0
echo "Creating the container for [${IMAGE}]..."
CONTAINER="$(docker create "${IMAGE}")" || fail "Failed to create the container (rc=${?})"
trap cleanup EXIT
ok "Container ready with ID ${CONTAINER}!"

SCRIPTS=(
	/.functions
	/usr/local/bin/decrypt
	/usr/local/bin/encrypt
	/usr/local/bin/find-ssl-dirs
	/usr/local/bin/fips-enabled
	/usr/local/bin/json2yaml
	/usr/local/bin/mvn-crypt
	/usr/local/bin/mvn-get
	/usr/local/bin/xmlenvsubst
	/usr/local/bin/yaml2json
)

doing "Copying the scripts..."
for SCRIPT in "${SCRIPTS[@]}" ; do
	docker cp "${CONTAINER}:${SCRIPT}" "${SCRIPT}" || fail "Failed to copy [${SCRIPT}] (rc=${?})"
done
ok "Scripts copied!"
