#!/bin/bash

set -euo pipefail

timestamp()
{
	/usr/bin/date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

doing()
{
	say "👉 ${@}"
}

ok()
{
	say "✅ ${@}"
}

warn()
{
	say "⚠️ ${@}"
}

err()
{
	say "❌ ${@}"
}

fail()
{
	err "${@}"
	exit ${EXIT_CODE:-1}
}

cleanup()
{
	[ -n "${CID:-}" ] && rm -rf "${CID}" &>/dev/null
	if [ -n "${CONTAINER:-}" ] ; then
		doing "Removing the created container (${CONTAINER}) ..."
		OUT="$(docker container rm --force --volumes "${CONTAINER}" 2>&1)" \
			&& ok "Cleanup complete!" \
			|| err "Couldn't remove the container [${CONTAINER}] (rc=${?}): ${OUT}"
	fi
}

if [ "$(/usr/bin/id -u)" != "0" ] ; then
	say "⚠️ Not running as root, must escalate privileges!"
	exec sudo -EH "PATH=${PATH}" "${0}" "${@}"
fi

REG="public.ecr.aws"
REPO="arkcase/base-container-scripts"
VER="latest"
IMAGE="${REG}/${REPO}:${VER}"

trap cleanup EXIT

echo "Creating the container for [${IMAGE}]..."
CID="$(mktemp --tmpdir=/tmp .container-id.XXXXXX 2>&1)" || fail "Failed to create a temporary file (rc=${?}): ${CID}"
rm -f "${CID}" &>/dev/null || true
CONTAINER="$(docker create --pull always --cidfile "${CID}" --entrypoint /dev/null "${IMAGE}" 2>&1)" || fail "Failed to create the container (rc=${?}): ${CONTAINER}"
CONTAINER="$(<"${CID}")" || fail "Failed to read the Container ID from [${CID}]"
ok "Container ready with ID ${CONTAINER}!"

doing "Copying the common-use scripts ..."
SRC_ITEMS=(
	.functions
	usr/local/bin/
)
for SRC in "${SRC_ITEMS[@]}" ; do
	doing "Installing [${SRC}] ..."
	OUT="$( docker cp "${CONTAINER}:/${SRC}" "/${SRC}" )" || fail "Failed to copy [${SRC}] (rc=${?}): ${OUT}"
	ok "Installed!"
done
