#!/bin/bash

set -euo pipefail

timestamp()
{
	date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

fail()
{
	say "❌ ${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

cleanup()
{
	[ -v KVS_TGT ] && rm -rf "${KVS_TGT}" &>/dev/null
}

if [ "$(/usr/bin/id -u)" != "0" ] ; then
	say "⚠️ Not running as root, must escalate privileges!"
	exec sudo -EH "PATH=${PATH}" "${0}" "${@}"
fi

KVS_VER="0.16.0"
KVS_SRC="https://github.com/elsesiy/kubectl-view-secret/releases/download/v${KVS_VER}/kubectl-view-secret_v${KVS_VER}_linux_amd64.tar.gz"
KVS_HASH="dad8f7d257e17e0a382f139bd756cdb437268d77973ad8ba3c55b346ce5bdd92"
KVS_EXE="kubectl-view-secret"

KVS_TGT="$(mktemp --tmpdir=/tmp kvs-XXXXXXXX.tar.gz 2>&1)" || fail "Failed to create a temporary file (rc=${?}): ${KVS_TGT}"
trap cleanup EXIT

curl -fsSL -o "${KVS_TGT}" "${KVS_SRC}" || fail "Failed to download kubectl-view-secret (rc=${?})"

OUT="$(tar -C /usr/local/bin -xvf "${KVS_TGT}" "${KVS_EXE}" 2>&1)" || fail "Failed to extract the executable [${KVS_EXE}] (rc=${?}): ${OUT}"

COMP="/usr/share/bash-completion/completions/${KVS_EXE}"
"${KVS_EXE}" completion bash > "${COMP}" || fail "Failed to create the bash completion file for [${KVS_EXE}]"
chmod a+r "${COMP}" || fail "Failed to make the completion file world-readable (rc=${?})"

exit 0
